var	nconf = module.parent.require('nconf'),
	Emoji = {
		mapping: {
			"(Kappa)": "kappa",
			"(BibleThump)": "biblethump",
			"(DansGame)": "dansgame",
			"(FrankerZ)": "frankerz",
			"(MrDestructoid)": "mrdestructoid",
			"(ShibeZ)": "shibez",
			"(BloodTrail)": "bloodtrail",
			"(FailFish)": "failfish",
			"(KAPOW)": "kapow",
			"(Keepo)": "keepo",
			"(PJSalt)": "pjsalt",
			"(SMOrc)": "smorc",
			"(TriHard)": "trihard",
			"(4Head)": "4head",
			"(aneleanele)": "aneleanele",
			"(ArsonNoSexy)": "arsonnosexy",
			"(AsianGlow)": "asianglow",
			"(AtGL)": "atgl",
			"(AtIvy)": "ativy",
			"(AtWW)": "atww",
			"(BabyRage)": "babyrage",
			"(BatChest)": "batchest",
			"(BCWarrior)": "bcwarrior",
			"(BigBrother)": "bigbrother",
			"(BionicBunion)": "bionicbunion",
			"(BlargNaut)": "blargnaut",
			"(BORT)": "bort",
			"(BrainSlug)": "brainslug",
			"(BrokeBack)": "brokeback",
			"(BuddhaBar)": "buddhabar",
			"(CougarHunt)": "cougarhunt",
			"(DAESuppy)": "daesuppy",
			"(DatSheffy)": "datsheffy",
			"(DBstyle)": "dbstyle",
			"(DogFace)": "dogface",
			"(EagleEye)": "eagleeye",
			"(EleGiggle)": "elegiggle",
			"(EvilFetus)": "evilfetus",
			"(FailFish)": "failfish",
			"(FPSMarksman)": "fpsmarksman",
			"(FreakinStinkin)": "freakinstinkin",
			"(FUNgineer)": "fungineer",
			"(FuzzyOtterOO)": "fuzzyotteroo",
			"(GasJoker)": "gasjoker",
			"(GingerPower)": "gingerpower",
			"(GrammarKing)": "grammarking",
			"(HassaanChop)": "hassaanchop",
			"(HassanChop)": "hassanchop",
			"(HotPokket)": "hotpokket",
			"(HumbleLife)": "humblelife",
			"(ItsBoshyTime)": "itsboshytime",
			"(Jebaited)": "jebaited",
			"(JKanStyle)": "jkanstyle",
			"(JonCarnage)": "joncarnage",
			"(KevinTurtle)": "kevinturtle",
			"(Kippa)": "kippa",
			"(Kreygasm)": "kreygasm",
			"(KZassault)": "kzassault",
			"(KZcover)": "kzcover",
			"(KZguerilla)": "kzguerilla",
			"(KZhelghast)": "kzhelghast",
			"(KZowl)": "kzowl",
			"(KZskull)": "kzskull",
			"(MechaSupes)": "mechasupes",
			"(MVGame)": "mvgame",
			"(NightBat)": "nightbat",
			"(NinjaTroll)": "ninjatroll",
			"(NoNoSpot)": "nonospot",
			"(noScope)": "noscope",
			"(OMGScoots)": "omgscoots",
			"(OneHand)": "onehand",
			"(OpieOP)": "opieop",
			"(OptimizePrime)": "optimizeprime",
			"(panicBasket)": "panicbasket",
			"(PanicVis)": "panicvis",
			"(PazPazowitz)": "pazpazowitz",
			"(PeoplesChamp)": "peopleschamp",
			"(PermaSmug)": "permasmug",
			"(PicoMause)": "picomause",
			"(PipeHype)": "pipehype",
			"(PJHarley)": "pjharley",
			"(PMSTwin)": "pmstwin",
			"(PogChamp)": "pogchamp",
			"(Poooound)": "poooound",
			"(PRChase)": "prchase",
			"(PunchTrees)": "punchtrees",
			"(RaccAttack)": "raccattack",
			"(RaplherZ)": "ralpherz",
			"(RedCoat)": "redcoat",
			"(ResidentSleeper)": "residentsleeper",
			"(RitzMitz)": "ritzmitz",
			"(RuleFive)": "rulefive",
			"(Shazam)": "shazam",
			"(shazamicon)": "shazamicon",
			"(ShazBotstix)": "shazbotstix",
			"(SMSkull)": "smskull",
			"(SoBayed)": "SoonerLater",
			"(SriHead)": "srihead",
			"(SSSsss)": "ssssss",
			"(StoneLightning)": "stonelightning",
			"(StrawBeary)": "strawbeary",
			"(SuperVinlin)": "supervinlin",
			"(SwiftRage)": "swiftrage",
			"(TehFunrun)": "tehfunrun",
			"(TF2John)": "tf2john",
			"(TheRinger)": "theringer",
			"(TheTarFu)": "thetarfu",
			"(TheThing)": "thething",
			"(ThunBeast)": "thunbeast",
			"(TinyFace)": "tinyface",
			"(TooSpicy)": "toospicy",
			"(UleetBackup)": "uleetbackup",
			"(UncleNox)": "unclenox",
			"(UnSane)": "unsane",
			"(Volcania)": "volcania",
			"(WholeWheat)": "wholewheat",
			"(WinWaker)": "winwaker",
			"(WTRuck)": "wtruck",
			"(WutFace)": "wutface",
			"(YouWHY)": "youwhy",
			":)": "smiley1",
			":(": "smiley2",
			":o": "smiley3",
			":z": "smiley4",
			"B)": "smiley5",
			":/": "smiley6",
			";)": "smiley7",
			";p": "smiley8",
			":p": "smiley9",
			"R)": "smiley10",
			"o_O": "smiley11",
			":D": "smiley12",
			">)": "smiley13",
			"<3": "smiley14",
		}
	};

	Emoji.replaceOutsideOfCode = function (content, pattern, cb) {
		return content.replace(/(^|<\/code>)([^<]*|<(?!code>))*(<code>|$)/g, function (match) {
			return match.replace(pattern, cb);
		});
	};

	Emoji.addEmoji = function (postContent, callback) {
		callback(null, Emoji.replaceOutsideOfCode(postContent,
			/&gt;:\)|\([\w~]+\)|\\[:]?[od]\/|[:;\|bBiIxX8\(\)\]][=\-"^:]?[)>$&|\w\(\)*@#?]?[)>$&|\w\(\)*@#?]/g,
			function (match) {
				match = match.replace('&gt;', '>');
				return Emoji.mapping[match] ? '<img class="nodebb-plugin-emoji-twitch" src="' +
					nconf.get('relative_path') + '/plugins/nodebb-plugin-emoji-twitch/icons/' +
					Emoji.mapping[match] + '.png" title="' + match + '"/>' : match;
			}
		));
	};

module.exports = Emoji;
